In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4]

In [4]:
arr = np.array(list1)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4]


In [7]:
nested_list = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Built in methods

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
#Used for neural networks
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Also used for neural networks
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0,10,50,dtype=int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#Used for weight initialization in neural networkds
np.random.rand(5,5)

array([[0.44590777, 0.66861074, 0.71935235, 0.52360048, 0.81054631],
       [0.44107578, 0.89413444, 0.14358382, 0.41308584, 0.04027435],
       [0.21886113, 0.04556425, 0.64158161, 0.69100192, 0.5787036 ],
       [0.8199659 , 0.00992153, 0.93147801, 0.19679136, 0.64520425],
       [0.69988165, 0.53505949, 0.65517945, 0.39660307, 0.65718308]])

In [22]:
np.random.randn(5,5)

array([[ 0.64388755, -0.31253948, -0.64526227,  0.01596641,  1.55482376],
       [ 0.56293801, -1.64795303,  0.18331129,  0.99340563,  1.29804413],
       [-0.49475404,  0.56011591,  0.15088844, -0.67218628,  0.36808873],
       [ 0.15986767,  0.58056995,  1.57971205, -0.97318764,  0.22626784],
       [ 0.41328679,  0.04120895,  1.47185129, -0.15989038, -0.19168685]])

In [23]:
np.random.randint(1,100,10)

array([14, 69, 31, 25, 13, 11, 91, 15, 66, 42])

In [25]:
arr1 = np.arange(25)
print(arr1.shape)

(25,)


Comma in the above output, because it is a vector not 1 dimensional array

In [26]:
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


The numbers belong to either 1 row or 1 column

In [29]:
arr1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

1 row, 25 columns

In [28]:
arr1.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

25 rows, 1 column

In [31]:
arr1 = arr1.reshape(5,5)

In [32]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr1 = arr1.transpose()

In [34]:
arr1

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [35]:
arr1 = arr1.T

In [36]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr2 = np.arange(50).reshape(5,10)


In [38]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr2 = arr2.T

In [40]:
arr2


array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [41]:
arr2.dtype

dtype('int64')

In [42]:
arr3 = np.arange(0,11)

In [43]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr3[8]

8

In [45]:
arr3[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr3[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr3[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr3[0:5] = 100

In [50]:
arr3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr4 = np.arange(0,11)

In [55]:
slice_of_arr = arr4[0:6]

In [56]:
slice_of_arr[:] = 99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Original array from which it was sliced also gets modified, because both slice and original array point to same location. This is shallow copy.

In [60]:
arr4

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr4 = np.arange(0,11)
arr_copy = arr4[0:6].copy()
arr_copy

array([0, 1, 2, 3, 4, 5])

In [64]:
arr_copy[:] = 99

In [65]:
arr_copy

array([99, 99, 99, 99, 99, 99])

This is a deep copy. So the original array does not get modified.

In [67]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [95]:
bool_2d = arr_2d > 10
arr_2d[bool_2d]

array([15, 20, 25, 30, 35, 40, 45])

In [84]:
arr_2d[1][0]

20

In [85]:
arr_2d.shape

(3, 3)

In [86]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [87]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [88]:
arr_2d[2,2]

45

In [92]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [91]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [97]:
arr = np.arange(0,10)

In [98]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Divide by 0 - nan

In [100]:
arr / arr

/home/monica/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [101]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Infinity for 1/arr

In [103]:
1/arr

/home/monica/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [104]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])